services:
  avfallsanteckning:
    image: ghcr.io/mews-se/avfallsanteckning:latest
    container_name: avfallsanteckning
    init: true
    restart: unless-stopped
    ports:
      - "8400:8400"
    volumes:
      - ./data:/data
      - ./config.toml:/config.toml:ro
